# Generated by Django 6.0.7 on 2026-08-19 03:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoExperienceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('rear-camera', 'Rear camera'), ('example-scenes', 'Example scenes')], default='rear-camera', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_experience_session', to=settings.AUTH_USER_MODEL)),
                ('template_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo_template_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='demo_session_expiry_idx'), models.Index(fields=['template_user', 'created_at'], name='demo_template_created_idx')],
            },
        ),
    ]
