# Generated by Django 6.0.7 on 2026-07-31 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfusionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confusion_type', models.CharField(choices=[('person', 'Person'), ('place', 'Place'), ('time', 'Time'), ('task', 'Task'), ('meal', 'Meal')], max_length=30)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confusion_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('unknown', 'Unknown')], max_length=20)),
                ('eaten_at', models.DateTimeField()),
                ('menu', models.CharField(blank=True, max_length=255, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('patient_confirmed', 'Patient Confirmed'), ('caregiver_recorded', 'Caregiver Recorded'), ('system_suggested', 'System Suggested')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-eaten_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealContextEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField()),
                ('is_meal_scene', models.BooleanField(blank=True, null=True)),
                ('meal_scene_probability', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('context_result', models.CharField(choices=[('non_meal_scene', 'Non Meal Scene'), ('meal_notice_suppressed', 'Meal Notice Suppressed'), ('recent_meal_found', 'Recent Meal Found'), ('meal_detected_without_record', 'Meal Detected Without Record')], max_length=50)),
                ('user_action', models.CharField(blank=True, choices=[('none', 'None'), ('view_record', 'View Record'), ('create_record', 'Create Record'), ('dismiss', 'Dismiss'), ('confirm', 'Confirm')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_context_events', to=settings.AUTH_USER_MODEL)),
                ('recent_meal_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_events', to='records.mealrecord')),
            ],
            options={
                'ordering': ['-detected_at', '-created_at'],
            },
        ),
    ]
