# Generated by Django 6.0.7 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrecord',
            name='scene_image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='meal-records/%Y/%m/%d/',
            ),
        ),
    ]
