"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import environ
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

env = environ.Env(
    DEBUG=(bool, False),
    LOCAL_ENVIRONMENT=(bool, False),
)

# .env를 기본으로 읽고, .env.local이 있으면 로컬 전용 값으로 덮어쓴다.
local_env_file = BASE_DIR / '.env.local'
default_env_file = BASE_DIR / '.env'

if default_env_file.exists():
    environ.Env.read_env(env_file=default_env_file)

if local_env_file.exists():
    environ.Env.read_env(env_file=local_env_file, overwrite=True)

SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
is_local_environment = env(
    'LOCAL_ENVIRONMENT',
    default=DEBUG or local_env_file.exists(),
)

# 온라인 전시용 데모 계정입니다. 실제 계정 정보를 프론트엔드에 노출하지 않고,
# 명시적으로 활성화된 경우에만 전용 로그인 API에서 토큰을 발급합니다.
DEMO_EXPERIENCE_ENABLED = env.bool('DEMO_EXPERIENCE_ENABLED', default=False)
DEMO_EXPERIENCE_USERNAME = env('DEMO_EXPERIENCE_USERNAME', default='')
DEMO_EXPERIENCE_SESSION_HOURS = env.int('DEMO_EXPERIENCE_SESSION_HOURS', default=72)


ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'people',
    'accounts',
    'records',
    'patient_assistant',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# 로컬 환경은 SQLite를, 배포 환경은 MySQL을 기본으로 사용한다.
# DB_ENGINE을 명시하면 해당 설정이 우선한다.
database_engine = env(
    'DB_ENGINE',
    default='sqlite' if is_local_environment else 'mysql',
).lower()

if database_engine == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / env('DB_NAME', default='db.sqlite3'),
        }
    }
elif database_engine == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST'),
            'PORT': env('DB_PORT', default='3306'),
        }
    }
else:
    raise ValueError('DB_ENGINE은 sqlite 또는 mysql이어야 합니다.')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (
        "accept",
        "authorization",
        "content-type",
        "user-agent",
        "x-csrftoken",
        "x-requested-with",
)

OPENAI_API_KEY = env('OPENAI_API_KEY', default=None)
OPENAI_TRANSCRIPTION_MODEL = env(
    'OPENAI_TRANSCRIPTION_MODEL',
    default='gpt-4o-mini-transcribe',
)
OPENAI_TRANSCRIPTION_DIARIZATION_ENABLED = env.bool(
    'OPENAI_TRANSCRIPTION_DIARIZATION_ENABLED',
    default=True,
)
OPENAI_TRANSCRIPTION_DIARIZATION_MODEL = env(
    'OPENAI_TRANSCRIPTION_DIARIZATION_MODEL',
    default='gpt-4o-transcribe-diarize',
)
OPENAI_TRANSCRIPTION_LANGUAGE = env('OPENAI_TRANSCRIPTION_LANGUAGE', default='ko')
OPENAI_PATIENT_QUESTION_CLASSIFICATION_MODEL = env(
    'OPENAI_PATIENT_QUESTION_CLASSIFICATION_MODEL',
    default='gpt-4o-mini',
)
OPENAI_MEMORY_REFLECTION_MODEL = env(
    'OPENAI_MEMORY_REFLECTION_MODEL',
    default='gpt-4.1',
)
OPENAI_TTS_MODEL = env('OPENAI_TTS_MODEL', default='tts-1')
OPENAI_TTS_VOICE = env('OPENAI_TTS_VOICE', default='alloy')
OPENAI_MEMORY_SUMMARY_MODEL = env('OPENAI_MEMORY_SUMMARY_MODEL', default='gpt-4o')
OPENAI_MEMORY_SUMMARY_MAX_OUTPUT_TOKENS = env.int(
        'OPENAI_MEMORY_SUMMARY_MAX_OUTPUT_TOKENS',
    default=700,
)
PROMISE_DEFAULT_TIMEZONE = env('PROMISE_DEFAULT_TIMEZONE', default='Asia/Seoul')
PROMISE_EXPIRED_RETENTION_DAYS = env.int(
    'PROMISE_EXPIRED_RETENTION_DAYS',
    default=30,
)

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES' : (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

REST_USER_JWT = True

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'ACCESS_TOKEN': 'access_token',
    'REFRESH_TOKEN': 'refresh_token',
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Gieoksaerok API",
    "DESCRIPTION": "기억새록 MVP API 문서",
    "VERSION": "v1",
    "SERVE_INCLUDE_SCHEMA": False,
}
