# Generated by Django 6.0.7 on 2026-07-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0003_normalize_person_uuid_ids"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="memory",
            index=models.Index(
                fields=["person", "-memory_at"], name="memory_person_recent_idx"
            ),
        ),
    ]
