# Generated by Django 6.0.7 on 2026-07-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0004_memory_memory_person_recent_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="core_memory",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
