# Generated by Django 6.0.7 on 2026-07-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0005_person_core_memory"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientVoiceProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("speaker_name", models.CharField(default="환자", max_length=80)),
                ("audio_data", models.BinaryField()),
                (
                    "audio_content_type",
                    models.CharField(default="audio/webm", max_length=100),
                ),
                (
                    "audio_filename",
                    models.CharField(blank=True, default="", max_length=160),
                ),
            ],
            options={
                "db_table": "patient_voice_profiles",
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="speaker_segments",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
