# Generated by Django 6.0.7 on 2026-07-31 05:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0006_patientvoiceprofile_conversation_speaker_segments"),
    ]

    operations = [
        migrations.CreateModel(
            name="LongTermMemory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("family", "Family"),
                            ("birth", "Birth"),
                            ("marriage", "Marriage"),
                            ("education", "Education"),
                            ("career", "Career"),
                            ("health", "Health"),
                            ("death", "Death"),
                            ("relationship", "Relationship"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("description", models.TextField()),
                ("event_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("confirmed", "Confirmed"),
                            ("archived", "Archived"),
                        ],
                        default="suggested",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0)),
                ("source_text", models.TextField(blank=True, default="")),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="long_term_memories",
                        to="people.conversation",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="long_term_memories",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "long_term_memories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["person", "status", "-created_at"],
                        name="ltm_person_status_recent_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PersonSummary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("card", models.JSONField()),
                ("source_memory_ids", models.JSONField(blank=True, default=list)),
                (
                    "source_long_term_memory_ids",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("stale", "Stale"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_summaries",
                        to="people.conversation",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "summaries",
                "ordering": ["-generated_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["person", "status", "-generated_at"],
                        name="summary_person_status_idx",
                    )
                ],
            },
        ),
    ]
