# Generated by Django 6.0.7 on 2026-07-31 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0007_longtermmemory_personsummary"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryAlbumItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("photo", models.FileField(upload_to="memory_album_photos/")),
                ("description", models.CharField(max_length=160)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_album_items",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "memory_album_items",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["person", "-created_at"], name="album_person_recent_idx"
                    )
                ],
            },
        ),
    ]
