# Generated by Django 6.0.7 on 2026-07-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0008_memoryalbumitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryalbumitem",
            name="crop_x",
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name="memoryalbumitem",
            name="crop_y",
            field=models.FloatField(default=50),
        ),
    ]
