# Generated by Django 6.0.7 on 2026-07-31 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0009_memoryalbumitem_crop_x_memoryalbumitem_crop_y"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="core_memory",
        ),
    ]
