# Generated by Django 6.0.7 on 2026-07-31 23:56

from django.db import migrations, models


def deduplicate_long_term_memories(apps, schema_editor):
    LongTermMemory = apps.get_model("people", "LongTermMemory")
    duplicate_keys = {}

    for memory in LongTermMemory.objects.all().order_by("person_id", "category"):
        key = (memory.person_id, memory.category)
        duplicate_keys.setdefault(key, []).append(memory)

    for memories in duplicate_keys.values():
        if len(memories) <= 1:
            continue

        memories.sort(
            key=lambda memory: (
                1 if memory.status == "confirmed" else 0,
                memory.confidence or 0,
                memory.updated_at,
                memory.created_at,
            ),
            reverse=True,
        )
        keeper = memories[0]
        duplicate_ids = [memory.id for memory in memories[1:]]
        LongTermMemory.objects.filter(id__in=duplicate_ids).delete()

        if not keeper.source_text:
            keeper.source_text = "중복 장기기억 정리 중 보존된 레코드입니다."
            keeper.save(update_fields=["source_text", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0010_remove_person_core_memory"),
    ]

    operations = [
        migrations.RunPython(
            deduplicate_long_term_memories,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="longtermmemory",
            constraint=models.UniqueConstraint(
                fields=("person", "category"), name="unique_ltm_person_category"
            ),
        ),
    ]
