# Generated by Django 6.0.7 on 2026-08-01 00:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0011_longtermmemory_unique_ltm_person_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="personsummary",
            name="source_promise_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="Promise",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("description", models.TextField()),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("time_label", models.CharField(blank=True, default="", max_length=80)),
                ("timezone", models.CharField(default="Asia/Seoul", max_length=64)),
                ("raw_text", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promises",
                        to="people.conversation",
                    ),
                ),
                (
                    "memory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promises",
                        to="people.memory",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promises",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "promises",
                "ordering": ["scheduled_at", "scheduled_date", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["person", "status", "scheduled_at"],
                        name="promise_person_status_at_idx",
                    ),
                    models.Index(
                        fields=["person", "status", "scheduled_date"],
                        name="promise_person_status_date_idx",
                    ),
                ],
            },
        ),
    ]
